int f=0;
void setup() {
  // put your setup code here, to run once:
  pinMode(5,OUTPUT);
  pinMode(4,OUTPUT);
  pinMode(3,OUTPUT);
  pinMode(2,OUTPUT);
  pinMode(11,OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  int a=analogRead(A0);
  Serial.println(a);
  delay(1);
  int b=analogRead(A1);
  Serial.println(b);
  delay(1);
  if(a>500&&f==0)
  {
    f=1;
    analogWrite(11,25);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a<500&&f==1)
  {
    f=2;
    analogWrite(11,25);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==2)
  {
    f=3;
    analogWrite(11,50);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a<500&&f==3)
  {
    f=4;
    analogWrite(11,50);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==4)
  {
    f=5;
    analogWrite(11,75);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==5)
  {
    f=6;
    analogWrite(11,75);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==6)
  {
    f=7;
    analogWrite(11,100);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==7)
  {
    f=8;
    analogWrite(11,100);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==8)
  {
    f=9;
    analogWrite(11,125);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==9)
  {
    f=10;
    analogWrite(11,125);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==10)
  {
    f=11;
    analogWrite(11,150);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==11)
  {
    f=12;
    analogWrite(11,150);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==12)
  {
    f=13;
    analogWrite(11,175);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==13)
  {
    f=14;
    analogWrite(11,175);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==14)
  {
    f=15;
    analogWrite(11,200);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==15)
  {
    f=16;
    analogWrite(11,200);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(a>500&&f==16)
  {
    f=17;
    analogWrite(11,255);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(a<500&&f==17)
  {
    f=18;
    analogWrite(11,255);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }








    if(b>500&&f==18)
  {
    f=19;
    analogWrite(11,250);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b<500&&f==19)
  {
    f=20;
    analogWrite(11,250);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==20)
  {
    f=21;
    analogWrite(11,225);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b<500&&f==21)
  {
    f=22;
    analogWrite(11,225);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==22)
  {
    f=23;
    analogWrite(11,200);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==23)
  {
    f=24;
    analogWrite(11,200);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==24)
  {
    f=25;
    analogWrite(11,175);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==25)
  {
    f=26;
    analogWrite(11,175);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==26)
  {
    f=27;
    analogWrite(11,150);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==27)
  {
    f=28;
    analogWrite(11,150);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==28)
  {
    f=29;
    analogWrite(11,125);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==29)
  {
    f=30;
    analogWrite(11,125);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==30)
  {
    f=31;
    analogWrite(11,100);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==31)
  {
    f=32;
    analogWrite(11,100);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==32)
  {
    f=33;
    analogWrite(11,75);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==33)
  {
    f=34;
    analogWrite(11,75);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
    if(b>500&&f==34)
  {
    f=35;
    analogWrite(11,50);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==35)
  {
    f=36;
    analogWrite(11,50);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b>500&&f==36)
  {
    f=37;
    analogWrite(11,25);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }
      if(b<500&&f==37)
  {
    f=37;
    analogWrite(11,25);
    digitalWrite(4,HIGH);
    digitalWrite(5,LOW);
    delay(10);
    digitalWrite(2,HIGH);
    digitalWrite(3,LOW);
  }


}
